### ISSUE TITLE
UserNotification support

### ISSUE THREAD

**Issue by yepesasecas** [danhper/pushex#7]
Im trying to send *mutable-content* and *attachment-url* to create a customized UserNotification.

but, I don't see this parameters arriving at my Swift App.

Im I doing something wrong? how should I send the *mutable-content*, no examples in documentation.

regards

**Comment by tuvistavie** [comment]
For APNS, I am delegating to https://github.com/chvanikoff/apns4ex, so you can pass anything it supports.
`mutable-content` can be passed as `mutable_content`, and I think `attachment-url` should be passed inside `extra`. Let me know how it works for you.

I am working on switching to the HTTP/2 API on another branch, but I am not done yet.
I am planning on keeping the upgrade to the HTTP/2 API backward compatible.

**Comment by tuvistavie** [comment]
Oh, you're right. I saw you opened an issue on the apns4ex side, let's upgrade when they release a new package.
I am working on the http/2 implementation of APNS in another branch, so hopefully in a later version we should be able to drop the dependency on this package.
